# Generated by Django 5.0.4 on 2024-12-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rates',
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('1', 'officials'), ('2', 'visitors')], default='2', max_length=50),
        ),
    ]
