# Generated by Django 5.0.4 on 2024-12-07 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0002_delete_rates_alter_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userrole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangay.user_roles', verbose_name='user roles'),
        ),
    ]
