# Generated by Django 5.0.4 on 2024-12-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0003_user_roles_user_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_roles',
            name='color',
        ),
    ]
