# Generated by Django 5.0.4 on 2024-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0006_alter_user_fname_alter_user_lname_alter_user_middle'),
    ]

    operations = [
        migrations.CreateModel(
            name='calibrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_hieght', models.IntegerField()),
                ('container_height', models.IntegerField()),
            ],
        ),
    ]
