# Generated by Django 5.0.4 on 2024-12-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0007_calibrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrations',
            name='container_height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calibrations',
            name='sensor_hieght',
            field=models.FloatField(),
        ),
    ]
