# Generated by Django 5.0.4 on 2024-12-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0008_alter_calibrations_container_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrations',
            old_name='container_height',
            new_name='heigh_threshold',
        ),
        migrations.AddField(
            model_name='calibrations',
            name='low_threshold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibrations',
            name='mediun_threshold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibrations',
            name='setting_height',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
