# Generated by Django 5.0 on 2024-12-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0009_rename_container_height_calibrations_heigh_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrations',
            name='heigh_threshold',
            field=models.FloatField(verbose_name='High Threshold'),
        ),
        migrations.AlterField(
            model_name='calibrations',
            name='low_threshold',
            field=models.FloatField(verbose_name='Low Threshold'),
        ),
        migrations.AlterField(
            model_name='calibrations',
            name='mediun_threshold',
            field=models.FloatField(verbose_name='Medium Threshold'),
        ),
        migrations.AlterField(
            model_name='calibrations',
            name='sensor_hieght',
            field=models.FloatField(verbose_name='Sensors Height'),
        ),
        migrations.AlterField(
            model_name='calibrations',
            name='setting_height',
            field=models.FloatField(verbose_name='Setting Height'),
        ),
    ]
