# Generated by Django 5.0.4 on 2024-12-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0005_user_middle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle',
            field=models.CharField(max_length=50, verbose_name='Middle Name'),
        ),
    ]
